-- Fix content_ideas table schema to support AI import
-- Add missing columns for content-mapping functionality

ALTER TABLE content_ideas 
ADD COLUMN IF NOT EXISTS platform VARCHAR(50),
ADD COLUMN IF NOT EXISTS format VARCHAR(100),
ADD COLUMN IF NOT EXISTS source_document VARCHAR(255),
ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN DEFAULT false;

-- Add comments for new columns
COMMENT ON COLUMN content_ideas.platform IS 'Social media platform (Instagram, Facebook, etc.)';
COMMENT ON COLUMN content_ideas.format IS 'Content format (Feed post, Story, Reel, etc.)';
COMMENT ON COLUMN content_ideas.source_document IS 'Source document name for AI-generated content';
COMMENT ON COLUMN content_ideas.ai_generated IS 'Flag indicating if content was generated by AI';

-- Create index for platform for better query performance
CREATE INDEX IF NOT EXISTS idx_content_ideas_platform ON content_ideas(platform);
CREATE INDEX IF NOT EXISTS idx_content_ideas_ai_generated ON content_ideas(ai_generated);
